# Copyright (C) 2023-2024 Advanced Micro Devices, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.16)

###    USER SETTINGS  START    ###
# Below settings can be customized
# User needs to edit it manually as per their needs.
###    DO NOT ADD OR REMOVE VARIABLES FROM THIS SECTION    ###
# -----------------------------------------
# Add any compiler definitions, they will be added as extra definitions
# Example : Adding VERBOSE=1 will pass -DVERBOSE=1 to the compiler.

set(USER_COMPILE_DEFINITIONS
"ARMR5=1"
"ISP_MCMv3=1"
"ISP8200_V2204=1"
"ISPVI_EXPAND_CHAN=1"
"ISP_SP2=1"
"ISP_2DNR_V5_V2=1"
"ISP_EEV2=1"
"ISP_FILTER=1"
"ISP_AEV2_V4=1"
"ISP_AE_SHADOW=1"
"ISP_DEMOSAIC2=1"
"ISP_GE=1"
"ISP_RGBGC=1"
"ISP_HIST256=1"
"ISP_HIST64=1"
"ISP_GTM=1"
"ISP_CPROC_10BIT=1"
"ISP_CPROC_SHD=1"
"ISP_LSC_V3=1"
"ISP_MI_PP_WRITE=1"
"ISP_DG=1"
"ISP_CCM_0507=1"
"ISP_AWB_0410=1"
"ISP_STA=1"
"ISP_STA_V2=1"
"ISP_WDR_V5_2=1"
"ISP_CMPD_24BIT=1"
"ISP_TPG=1"
"ISP_MIV3=1"
"ISP_MCM=1"
"DEBUG_ENABLE_MBOX=1"
"FMC_PS_IIC=1"
"FREERTOS=1"
"ISP_RGBIR_V2_1=1"
"ISP_FUSA_MECHANISM=1"
"DUMP_IMAGE=1"
"NO_TERMINAL=1"
"ISP_GC_V2=1"
#"ISP_MPCTL_V1_1=1"
"ISP_MCM_UPDATE_SPLIT=1"
#"I2C_SLOW_MODE=1"
"I2C_FAST_MODE=1"
"ISP_VNC=1"
#"FRAME_RATE_DEBUG=1"
"ISP_PRIV_MEM=1"
"ELF_FLAG=${GEN_ELF}"
)

# Undefine any previously specified compiler definitions, either built in or provided with a -D option
# Example : Adding MY_SYMBOL will pass -UMY_SYMBOL to the compiler.
set(USER_UNDEFINED_SYMBOLS
"__clang__"
)


# Add any directories below, they will be added as extra include directories.
# Example 1: Adding /proj/data/include will pass -I/proj/data/include.
# Example 2: Adding ../../common/include will consider the path as relative to this component directory.
# Example 3: Adding ${CMAKE_SOURCE_DIR}/data/include to add data/include from this project.

set(USER_INCLUDE_DIRECTORIES
"${CMAKE_SOURCE_DIR}/file_system/include"
"${CMAKE_SOURCE_DIR}/file_system/portable"
"${CMAKE_SOURCE_DIR}/file_system/portable/common"
"${CMAKE_SOURCE_DIR}/platform"
"${CMAKE_SOURCE_DIR}/mbox/include"
"${CMAKE_SOURCE_DIR}/src"
"${CMAKE_SOURCE_DIR}/control/include"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/ae/include"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/ae/include_priv"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/af/include"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/af/include_priv"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/awb/include"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/awb/include_priv"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3a_ctrl/common/include"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/include"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/include/ae"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/include/af"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/include/awb"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/lib/vsi3aV4/include/ae"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/lib/vsi3aV4/include/af"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/lib/vsi3aV4/include/awb"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/lib/vsi3aV4/include/common"
"${CMAKE_SOURCE_DIR}/units/3a/3AV4/3ai/lib/vsi3aV4/include/logic"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/2dnrv5_2/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/2dnrv5_2/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/bls/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/bls/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/ccmv1_1/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/ccmv1_1/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/cproc/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/cproc/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/demosaic2/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/demosaic2/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/dpcc/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/dpcc/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/eev2/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/eev2/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/gcv2/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/gcv2/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/gtm/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/gtm/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/ge/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/ge/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/lscv3/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/lscv3/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/lut3d/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/lut3d/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/rgbirV2_1/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/rgbirV2_1/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/wdr5_2/include"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/wdr5_2/include_priv"
"${CMAKE_SOURCE_DIR}/units/binder/api/include"
"${CMAKE_SOURCE_DIR}/units/binder/common/include"
"${CMAKE_SOURCE_DIR}/units/binder/general/include"
"${CMAKE_SOURCE_DIR}/units/binder/tile_mode/include"
"${CMAKE_SOURCE_DIR}/units/buffer_management/include"
"${CMAKE_SOURCE_DIR}/units/cam_calibdb/include"
"${CMAKE_SOURCE_DIR}/units/cam_calibdb/include_priv"
"${CMAKE_SOURCE_DIR}/units/cam_device/config"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/control"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/2dnr_v5_2"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/ae_v4"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/awb_v4"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/bls"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/ccm_v1_1"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/cpd"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/cproc"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/dg"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/dmsc_v2"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/dpcc"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/dummy"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/ee_v2"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/exp_v2"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/flexa"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/fusa"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/gc_v2"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/ge"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/gtm_v1"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/hist"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/lsc_v3"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/pdaf_v1"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/rgbir_v2_1"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/tpg"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/wb_v1_1"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module/wdr_v5_2"
"${CMAKE_SOURCE_DIR}/units/cam_device/include/module"
"${CMAKE_SOURCE_DIR}/units/cam_device/include_priv/control"
"${CMAKE_SOURCE_DIR}/units/cam_device/include_priv/module/dummy"
"${CMAKE_SOURCE_DIR}/units/cam_device/include_priv/module/rgbir_v2_1"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/2dnr_v5_2"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/ae_v4"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/af_v4"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/afm_v1"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/awb_v4"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/bls"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/ccm_v11"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/cmpd_v11"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/cproc"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/csm"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/dci"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/demosaic_v2"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/dg"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/dpcc"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/dummy"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/eev2"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/expv2"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/fusa"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/gamma_curveV2"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/ge"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/gtm"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/hist64"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/hist256"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/lscv3"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/rgbirV2_1"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/video_in"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/wb_v11"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/wdr5_2"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/2dnrV5_V2/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/2dnrV5_V2/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/afmv1/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/afmv1/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/afmv1_v1/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/afmv1_v1/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/base/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/base/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/compand/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/compand/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/demosaicV2/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/demosaicV2/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/dg/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/dg/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/eev2/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/eev2/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/febe/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/febe/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/fusa/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/fusa/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/gcV2/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/gcV2/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/gtm/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/gtm/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/hdr_dummy/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/hdr_dummy/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/hist64/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/hist64/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/hist256/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/hist256/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/lscV1/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/lscV1/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/lscV3/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/lscV3/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/lut3d/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/lut3d/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/miV3/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/miV3/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/raw_cropV1/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/raw_cropV1/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/wb/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/wb/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/wdr5/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/wdr5/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/ynr/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/ynr/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_reg_drv/include"
"${CMAKE_SOURCE_DIR}/units/cameric_reg_drv/include_priv"
"${CMAKE_SOURCE_DIR}/units/cascade/include"
"${CMAKE_SOURCE_DIR}/units/common/include"
"${CMAKE_SOURCE_DIR}/units/ebase/include"
"${CMAKE_SOURCE_DIR}/units/isi/include"
"${CMAKE_SOURCE_DIR}/units/isi/include_priv"
"${CMAKE_SOURCE_DIR}/units/isi/sensor_drv"
"${CMAKE_SOURCE_DIR}/units/isi/sensor_drv/OS08a20/include_priv"
"${CMAKE_SOURCE_DIR}/units/isp_cmd_buffer/include"
"${CMAKE_SOURCE_DIR}/units/isp_cmd_buffer/include_priv"
"${CMAKE_SOURCE_DIR}/units/isp_drv/include"
"${CMAKE_SOURCE_DIR}/units/isp_drv/include_priv"
"${CMAKE_SOURCE_DIR}/units/isp_start_engine/isp_start_engine_api/include"
"${CMAKE_SOURCE_DIR}/units/isp_start_engine/isp_start_engine_v2/include"
"${CMAKE_SOURCE_DIR}/units/isp_start_engine/isp_start_engine_v3/include"
"${CMAKE_SOURCE_DIR}/units/isp_switch/include"
"${CMAKE_SOURCE_DIR}/units/isp_switch/include_priv"
"${CMAKE_SOURCE_DIR}/units/mkrel/common/include"
"${CMAKE_SOURCE_DIR}/units/oslayer/include"
"${CMAKE_SOURCE_DIR}/units/version/include"
"${CMAKE_SOURCE_DIR}/units/video_in/base/include"
"${CMAKE_SOURCE_DIR}/units/video_in/base/include_priv"
"${CMAKE_SOURCE_DIR}/units/vin_drv/include"
"${CMAKE_SOURCE_DIR}/units/vin_drv/include_priv"
"${CMAKE_SOURCE_DIR}/units/virtual_hal/api/include"
"${CMAKE_SOURCE_DIR}/units/virtual_hal/batch_mode/include"
"${CMAKE_SOURCE_DIR}/units/virtual_hal/general/include"
"${CMAKE_SOURCE_DIR}/units/virtual_hal/mcm/include"
"${CMAKE_SOURCE_DIR}/units/isp_switch/com"
"${CMAKE_SOURCE_DIR}/units/isp_cmd_buffer/include_priv/ISP8200_V2204_FUSA"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/rgbirV2_1/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/rgbirV2_1/include_priv"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/mpctlV1_1/include"
"${CMAKE_SOURCE_DIR}/units/cameric_drv/mpctlV1_1/include_priv"
"${CMAKE_SOURCE_DIR}/units/auto_ctrol/common"
"${CMAKE_SOURCE_DIR}/units/cam_engine/include/mpctlV1_1"
"${CMAKE_SOURCE_DIR}/units/binder/tile_mode/include_priv"
"${CMAKE_SOURCE_DIR}/hal/include"
"${CMAKE_SOURCE_DIR}/hal/include_priv"
"${CMAKE_SOURCE_DIR}/oba_drv"
"${CMAKE_SOURCE_DIR}/iba_drv"
"${CMAKE_SOURCE_DIR}/Main"
"${CMAKE_SOURCE_DIR}/Import_25.1_bsp/AXI_IIC"
)

set(USER_COMPILE_SOURCES
"Import_25.1_bsp/AXI_IIC/xiic.c"
"Import_25.1_bsp/AXI_IIC/xiic_dyn_master.c"
"Import_25.1_bsp/AXI_IIC/xiic_g.c"
"Import_25.1_bsp/AXI_IIC/xiic_intr.c"
"Import_25.1_bsp/AXI_IIC/xiic_l.c"
"Import_25.1_bsp/AXI_IIC/xiic_master.c"
"Import_25.1_bsp/AXI_IIC/xiic_multi_master.c"
"Import_25.1_bsp/AXI_IIC/xiic_options.c"
"Import_25.1_bsp/AXI_IIC/xiic_selftest.c"
"Import_25.1_bsp/AXI_IIC/xiic_sinit.c"
"Import_25.1_bsp/AXI_IIC/xiic_slave.c"
"Import_25.1_bsp/AXI_IIC/xiic_stats.c"
"Testapp/Spinlock_verify/spinlock_verify.c"
"atm_drv/atm_slcr.c"
"control/source/control.c"
"control/source/ctrl_2dnr_api_v5_2.c"
"control/source/ctrl_ae_api.c"
"control/source/ctrl_af_api_v1.c"
"control/source/ctrl_afm_api.c"
"control/source/ctrl_awb_api.c"
"control/source/ctrl_bls_api.c"
"control/source/ctrl_buffer_api.c"
"control/source/ctrl_ccm_api.c"
"control/source/ctrl_cpd_api.c"
"control/source/ctrl_cproc_api.c"
"control/source/ctrl_dg_api.c"
"control/source/ctrl_dmsc_api.c"
"control/source/ctrl_dpcc_api.c"
"control/source/ctrl_ee_api.c"
"control/source/ctrl_exp_api_v2.c"
"control/source/ctrl_fusa_api.c"
"control/source/ctrl_gc_api.c"
"control/source/ctrl_ge_api.c"
"control/source/ctrl_gtm_api.c"
"control/source/ctrl_hdr_api.c"
"control/source/ctrl_lsc_api.c"
"control/source/ctrl_rgbir_api.c"
"control/source/ctrl_sensor_api.c"
"control/source/ctrl_submodule_common.c"
"control/source/ctrl_wb_api.c"
"control/source/ctrl_wdr_api.c"
"hal/source/hal_altera_irq_notifier.c"
"hal/source/hal_altera_pci.c"
"hal/source/hal_altera_pci_mem.c"
"hal/source/hal_axi_i2c.c"
"hal/source/hal_common.c"
"hal/source/hal_i2c.c"
"hal/source/hal_irq.c"
"hal/source/hal_isp.c"
"hal/source/hal_mem.c"
"hal/source/hal_mipi.c"
"hal/source/hal_ps_i2c.c"
"hal/source/os_spinlock.c"
"iba_drv/iba.c"
"Main/main.c"
"mbox/source/mbox_api.c"
"mbox/source/mbox_cmd.c"
"mbox/source/mbox_fifo.c"
"mbox/source/sensor_cmd.c"
"oba_drv/oba.c"
"platform/cpu_info.c"
"platform/amp.c"
"platform/xil_tr_spinlock.c"
"Testapp/backtrace/backtrace.c"
"Testapp/control_testapp/control_testapp.c"
"Testapp/mbox_testapp/mbox_testapp.c"
"Testapp/oslayer_testapp/oslayer_test_app.c"
"Testapp/Pipeline/pipeline.c"
"Testapp/xil_threadsafe/xil_threadsafe_api.c"
"units/3a/3AV4/3a_ctrl/ae/source/ae_ctrl.c"
"units/3a/3AV4/3a_ctrl/af/source/af_ctrl.c"
"units/3a/3AV4/3a_ctrl/af/source/pdaf_statistic_cal.c"
"units/3a/3AV4/3a_ctrl/awb/source/awb_ctrl.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/ae/aec.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/af/af.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/vsi_ae_lib.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/awb/awb.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/vsi_af_lib.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/common/vsi3a_common.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/vsi_awb_lib.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/logic/vsi3a.c"
"units/3a/3AV4/3ai/lib/vsi3aV4/source/logic/vsi3a_control.c"
"units/3a/3AV4/3ai/source/ae/aei.c"
"units/3a/3AV4/3ai/source/af/afi.c"
"units/3a/3AV4/3ai/source/awb/awbi.c"
"units/auto_ctrol/2dnrv5_2/source/2dnr.c"
"units/auto_ctrol/bls/source/bls.c"
"units/auto_ctrol/ccmv1_1/source/ccm.c"
"units/auto_ctrol/common/common.c"
"units/auto_ctrol/cproc/source/cproc.c"
"units/auto_ctrol/demosaic2/source/demosaic2.c"
"units/auto_ctrol/dpcc/source/dpcc.c"
"units/auto_ctrol/eev2/source/ca.c"
"units/auto_ctrol/eev2/source/dci.c"
"units/auto_ctrol/eev2/source/ee.c"
"units/auto_ctrol/ge/source/ge.c"
"units/auto_ctrol/gcv2/source/gcv2.c"
"units/auto_ctrol/gtm/source/gtm.c"
"units/auto_ctrol/lscv3/source/lsc.c"
"units/auto_ctrol/rgbirV2_1/source/rgbir.c"
"units/auto_ctrol/wdr5_2/source/wdr5_2.c"
"units/binder/api/source/binder_hal_api.c"
"units/binder/common/source/binder_common_lsc.c"
"units/binder/general/source/binder_general_api.c"
"units/binder/tile_mode/source/afm/binder_tile_mode_afmv1.c"
"units/binder/tile_mode/source/afm/binder_tile_mode_afmv1_1.c"
"units/binder/tile_mode/source/binder_tile_mode_api.c"
"units/binder/tile_mode/source/awb/binder_tile_mode_awb.c"
"units/binder/tile_mode/source/binder_tile_mode_crop.c"
"units/binder/tile_mode/source/dmsc/binder_tile_mode_dmsc_cac.c"
"units/binder/tile_mode/source/binder_tile_mode_digital.c"
"units/binder/tile_mode/source/exp/binder_tile_mode_expv2.c"
"units/binder/tile_mode/source/binder_tile_mode_dpcc.c"
"units/binder/tile_mode/source/lsc/binder_tile_mode_lscv3.c"
"units/binder/tile_mode/source/lsc/binder_tile_mode_lscv4.c"
"units/binder/tile_mode/source/binder_tile_mode_hist.c"
"units/binder/tile_mode/source/wdr/binder_tile_mode_wdrv52.c"
"units/binder/tile_mode/source/binder_tile_mode_hist64.c"
"units/binder/tile_mode/source/binder_tile_mode_is.c"
"units/binder/tile_mode/source/binder_tile_mode_isp.c"
"units/binder/tile_mode/source/binder_tile_mode_mi.c"
"units/binder/tile_mode/source/binder_tile_mode_mpctl.c"
"units/binder/tile_mode/source/binder_tile_mode_mpctlV1_1.c"
"units/binder/tile_mode/source/binder_tile_mode_rgbgc.c"
"units/binder/tile_mode/source/binder_tile_mode_sta.c"
"units/buffer_management/source/buf_mgmt.c"
"units/buffer_management/source/buf_mgmt_pool.c"
"units/cam_calibdb/source/cam_calibdb.c"
"units/cam_calibdb/source/cam_calibdb_api.c"
"units/cam_device/source/control/cam_device.c"
"units/cam_device/source/control/cam_device_api.c"
"units/cam_device/source/control/cam_device_buffer.c"
"units/cam_device/source/control/cam_device_buffer_api.c"
"units/cam_device/source/control/cam_device_calib_api.c"
"units/cam_device/source/control/cam_device_isp_system_api.c"
"units/cam_device/source/control/cam_device_ispcore.c"
"units/cam_device/source/control/cam_device_sensor.c"
"units/cam_device/source/module/cam_device_module_api.c"
"units/cam_device/source/control/cam_device_sensor_api.c"
"units/cam_device/source/module/2dnr/cam_device_2dnr_api_v5_2.c"
"units/cam_device/source/module/ae/cam_device_ae_api_v4.c"
"units/cam_device/source/module/awb/cam_device_awb_api_v4.c"
"units/cam_device/source/module/bls/cam_device_bls_api.c"
"units/cam_device/source/module/ccm/cam_device_ccm_api_v1_1.c"
"units/cam_device/source/module/cpd/cam_device_cpd_api_v1.c"
"units/cam_device/source/module/cproc/cam_device_cproc_api.c"
"units/cam_device/source/module/dg/cam_device_dg_api_v1.c"
"units/cam_device/source/module/dmsc/cam_device_dmsc_api_v2.c"
"units/cam_device/source/module/dpcc/cam_device_dpcc_api.c"
"units/cam_device/source/module/dummy/cam_device_3dnr_api.c"
"units/cam_device/source/module/dummy/cam_device_af_api.c"
"units/cam_device/source/module/dummy/cam_device_afm_api.c"
"units/cam_device/source/module/dummy/cam_device_cnr_api.c"
"units/cam_device/source/module/dummy/cam_device_hdr.c"
"units/cam_device/source/module/dummy/cam_device_hdr_api.c"
"units/cam_device/source/module/ee/cam_device_ee_api_v2.c"
"units/cam_device/source/module/exp/cam_device_exp_api_v2.c"
"units/cam_device/source/module/fusa/cam_device_fusa_api_v1.c"
"units/cam_device/source/module/gc/cam_device_gc_api_v2.c"
"units/cam_device/source/module/ge/cam_device_ge_api.c"
"units/cam_device/source/module/gtm/cam_device_gtm_api_v1.c"
"units/cam_device/source/module/hist/cam_device_hist64_api.c"
"units/cam_device/source/module/hist/cam_device_hist256_api.c"
"units/cam_device/source/module/lsc/cam_device_lsc_api_v3.c"
"units/cam_device/source/module/rgbir/cam_device_rgbir_api_v2_1.c"
"units/cam_device/source/module/rgbir/cam_device_rgbir_v2_1.c"
"units/cam_device/source/module/tpg/cam_device_tpg_api.c"
"units/cam_device/source/module/wb/cam_device_wb_api_v1_1.c"
"units/cam_device/source/module/wdr/cam_device_wdr_api_v5_2.c"
"units/cam_engine/source/2dnr_v5_2/cam_engine_2dnr_api.c"
"units/cam_engine/source/cam_engine.c"
"units/cam_engine/source/ae_v4/cam_engine_ae_api.c"
"units/cam_engine/source/cam_engine_aaa_api.c"
"units/cam_engine/source/af_v4/cam_engine_af_api.c"
"units/cam_engine/source/cam_engine_api.c"
"units/cam_engine/source/afm_v1/cam_engine_afmv1_api.c"
"units/cam_engine/source/cam_engine_cb.c"
"units/cam_engine/source/awb_v4/cam_engine_awb_api.c"
"units/cam_engine/source/cam_engine_drv.c"
"units/cam_engine/source/bls/cam_engine_bls_api.c"
"units/cam_engine/source/cam_engine_isp_api.c"
"units/cam_engine/source/ccm_v11/cam_engine_ccm_api.c"
"units/cam_engine/source/cam_engine_mi_api.c"
"units/cam_engine/source/cmpd_v11/cam_engine_cmpd_api.c"
"units/cam_engine/source/cam_engine_modules.c"
"units/cam_engine/source/cproc/cam_engine_cproc_api.c"
"units/cam_engine/source/cam_engine_reg_api.c"
"units/cam_engine/source/csm/cam_engine_csm_api.c"
"units/cam_engine/source/cam_engine_subctrls.c"
"units/cam_engine/source/demosaic_v2/cam_engine_demosaic2_api.c"
"units/cam_engine/source/cam_engine_tpg_api.c"
"units/cam_engine/source/dg/cam_engine_dg_api.c"
"units/cam_engine/source/dpcc/cam_engine_dpcc_api.c"
"units/cam_engine/source/dummy/cam_engine_raw_crop_api.c"
"units/cam_engine/source/dummy/cam_engine_3dnr_api.c"
"units/cam_engine/source/eev2/cam_engine_ee_api.c"
"units/cam_engine/source/expv2/cam_engine_expv2_api.c"
"units/cam_engine/source/fusa/cam_engine_fusa_mechanism_api.c"
"units/cam_engine/source/gamma_curveV2/cam_engine_gamma_curve_api.c"
"units/cam_engine/source/ge/cam_engine_ge_api.c"
"units/cam_engine/source/gtm/cam_engine_gtm_api.c"
"units/cam_engine/source/hist64/cam_engine_hist64_api.c"
"units/cam_engine/source/hist256/cam_engine_hist256_api.c"
"units/cam_engine/source/lscv3/cam_engine_lsc_api.c"
"units/cam_engine/source/mpctlV1_1/cam_engine_mpctl.c"
"units/cam_engine/source/rgbirV2_1/cam_engine_rgbir_api.c"
"units/cam_engine/source/video_in/cam_engine_video_in_api.c"
"units/cam_engine/source/wb_v11/cam_engine_wb_api.c"
"units/cam_engine/source/wdr5_2/cam_engine_wdr5_2_api.c"
"units/cameric_drv/2dnrV5_V2/source/cameric_isp_2dnr.c"
"units/cameric_drv/afmv1/source/cameric_isp_afm.c"
"units/cameric_drv/base/source/cameric.c"
"units/cameric_drv/base/source/cameric_isp.c"
"units/cameric_drv/base/source/cameric_isp_ccm.c"
"units/cameric_drv/base/source/cameric_isp_cproc.c"
"units/cameric_drv/base/source/cameric_isp_crop.c"
"units/cameric_drv/base/source/cameric_isp_csm.c"
"units/cameric_drv/base/source/cameric_isp_degamma.c"
"units/cameric_drv/base/source/cameric_isp_dpcc.c"
"units/cameric_drv/base/source/cameric_isp_expv2.c"
"units/cameric_drv/base/source/cameric_isp_ge.c"
"units/cameric_drv/base/source/cameric_isp_is.c"
"units/cameric_drv/base/source/cameric_isp_sta.c"
"units/cameric_drv/base/source/cameric_isp_stitching_exp.c"
"units/cameric_drv/base/source/cameric_isp_stitching_hist.c"
"units/cameric_drv/base/source/cameric_isp_tpg.c"
"units/cameric_drv/base/source/cameric_scale.c"
"units/cameric_drv/compand/source/cameric_isp_compand.c"
"units/cameric_drv/demosaicV2/source/cameric_isp_dmsc2.c"
"units/cameric_drv/dg/source/cameric_isp_dg.c"
"units/cameric_drv/eev2/source/cameric_isp_eev2.c"
"units/cameric_drv/febe/source/cameric_isp_gamma_febe.c"
"units/cameric_drv/fusa/source/cameric_isp_fusa_mechanism.c"
"units/cameric_drv/fusa/source/cameric_isp_fusa_mechanism_2.c"
"units/cameric_drv/gcV2/source/cameric_isp_gcv2.c"
"units/cameric_drv/gtm/source/cameric_isp_gtm.c"
"units/cameric_drv/hdr_dummy/source/cameric_isp_stitching.c"
"units/cameric_drv/hist64/source/cameric_isp_hist64.c"
"units/cameric_drv/hist256/source/cameric_isp_hist256.c"
"units/cameric_drv/lscV3/source/cameric_isp_lsc.c"
"units/cameric_drv/miV3/source/cameric_mi.c"
"units/cameric_drv/miV3/source/cameric_mi_hdr.c"
"units/cameric_drv/miV3/source/cameric_mi_rdma.c"
"units/cameric_drv/miV3/source/cameric_mi_sub_system.c"
"units/cameric_drv/miV3/source/cameric_miv3.c"
"units/cameric_drv/mpctlV1_1/source/cameric_isp_mpctl.c"
"units/cameric_drv/rgbirV2_1/source/cameric_isp_rgbir.c"
"units/cameric_drv/wb/source/cameric_isp_wb.c"
"units/cameric_drv/wdr5/source/cameric_isp_wdr5.c"
"units/cameric_reg_drv/source/cameric_reg_description.c"
"units/cascade/src/sub_cascade.c"
"units/common/source/cea_861.c"
"units/common/source/hdmi_3d.c"
"units/common/source/picture_buffer.c"
"units/common/source/utl_explogarithm.c"
"units/common/source/utl_fixfloat.c"
"units/ebase/source/builtins.c"
"units/ebase/source/dct_assert.c"
"units/ebase/source/offline_trace.c"
"units/ebase/source/slist.c"
"units/ebase/source/trace.c"
"units/isi/source/isi.c"
"units/isp_cmd_buffer/source/isp_cmd_buffer.c"
"units/isp_cmd_buffer/source/isp_cmd_buffer_api.c"
"units/isp_drv/source/isp_2dnr/isp_2dnr5_2.c"
"units/isp_drv/source/isp_dmsc/isp_dmsc2.c"
"units/isp_drv/source/isp_afm.c"
"units/isp_drv/source/isp_ee/isp_eev2.c"
"units/isp_drv/source/isp_lsc/isp_lscv3.c"
"units/isp_drv/source/isp_awb.c"
"units/isp_drv/source/isp_lut3d/isp_3dlut.c"
"units/isp_drv/source/isp_mi/isp_miv3.c"
"units/isp_drv/source/isp_ccm.c"
"units/isp_drv/source/isp_wdr/isp_wdr5_2.c"
"units/isp_drv/source/isp_wdr/isp_wdr5_3.c"
"units/isp_drv/source/mpctl/isp_mp_ctlV1_1.c"
"units/isp_drv/source/isp_cnr2.c"
"units/isp_drv/source/isp_compand.c"
"units/isp_drv/source/isp_cproc.c"
"units/isp_drv/source/isp_crop.c"
"units/isp_drv/source/isp_csm.c"
"units/isp_drv/source/isp_dg.c"
"units/isp_drv/source/isp_dpcc.c"
"units/isp_drv/source/isp_drv_cmd.c"
"units/isp_drv/source/isp_expv2.c"
"units/isp_drv/source/isp_fusa.c"
"units/isp_drv/source/isp_gamma_febe.c"
"units/isp_drv/source/isp_gcv2.c"
"units/isp_drv/source/isp_ge.c"
"units/isp_drv/source/isp_gtm.c"
"units/isp_drv/source/isp_hdr_exp.c"
"units/isp_drv/source/isp_hdr_hist.c"
"units/isp_drv/source/isp_hist64.c"
"units/isp_drv/source/isp_hist256.c"
"units/isp_drv/source/isp_is.c"
"units/isp_drv/source/isp_mi_common.c"
"units/isp_drv/source/isp_mi_hdr.c"
"units/isp_drv/source/isp_mi_rdma.c"
"units/isp_drv/source/isp_rdcd.c"
"units/isp_drv/source/isp_rgbir2_1.c"
"units/isp_drv/source/isp_sta.c"
"units/isp_drv/source/isp_tpg.c"
"units/isp_start_engine/isp_start_engine_api/source/isp_start_engine_api.c"
"units/isp_start_engine/isp_start_engine_v2/source/isp_fe_func.c"
"units/isp_start_engine/isp_start_engine_v2/source/isp_start_engine_sw_api.c"
"units/isp_start_engine/isp_start_engine_v3/source/isp_hw_mcm.c"
"units/isp_start_engine/isp_start_engine_v3/source/isp_start_engine_hw_api.c"
"units/isp_switch/com/priority_queue.c"
"units/isp_switch/source/isp_switch.c"
"units/isp_switch/source/isp_switch_api.c"
"units/mkrel/common/source/core_type_check.c"
"units/oslayer/source/oslayer_freertos.c"
"units/oslayer/source/oslayer_generic.c"
"units/oslayer/source/oslayer_linux.c"
"units/oslayer/source/oslayer_mfs.c"
"units/oslayer/source/oslayer_systemc.c"
"units/oslayer/source/oslayer_ucosii.c"
"units/oslayer/source/oslayer_win32.c"
"units/version/source/version.c"
"units/video_in/base/source/isp_mcm.c"
"units/video_in/base/source/video_in_api.c"
"units/vin_drv/source/vin_drv.c"
"units/vin_drv/source/vin_drv_api.c"
"units/virtual_hal/api/source/virtual_hal_api.c"
"units/virtual_hal/general/source/virtual_general_api.c"
"units/virtual_hal/mcm/source/virtual_mcm_api.c"
)

# -----------------------------------------

# Turn on all optional warnings (-Wall)
set(USER_COMPILE_WARNINGS_ALL -Wall)

# Enable extra warning flags (-Wextra)
set(USER_COMPILE_WARNINGS_EXTRA -Wextra)

# Make all warnings into hard errors (-Werror)
set(USER_COMPILE_WARNINGS_AS_ERRORS )

# Check the code for syntax errors, but don't do anything beyond that (-fsyntax-only)
set(USER_COMPILE_WARNINGS_CHECK_SYNTAX_ONLY )

# Issue all the mandatory diagnostics listed in the C standard (-pedantic)
set(USER_COMPILE_WARNINGS_PEDANTIC )

# Issue all the mandatory diagnostics, and make all mandatory diagnostics into errors. (-pedantic-errors)
set(USER_COMPILE_WARNINGS_PEDANTIC_AS_ERRORS )

# Suppress all warnings (-w)
set(USER_COMPILE_WARNINGS_INHIBIT_ALL )

# -----------------------------------------

# Optimization level   "-O0" [None], "-O1" [Optimize] , "-O2" [Optimize More], "-O3" [Optimize Most] or "-Os" [Optimize Size]
set(USER_COMPILE_OPTIMIZATION_LEVEL -O0)

# Other flags related to optimization
set(USER_COMPILE_OPTIMIZATION_OTHER_FLAGS )

# -----------------------------------------

# Debug level "" [None], "-g1" [Minimum], "g2" [Default], "g3" [Maximum]
if(GEN_ELF)
set(USER_COMPILE_DEBUG_LEVEL -g3)
else()
set(USER_COMPILE_DEBUG_LEVEL )
endif()

# Other flags related to debugging
if(GEN_ELF)
set(USER_COMPILE_DEBUG_OTHER_FLAGS )
else()
set(USER_COMPILE_DEBUG_OTHER_FLAGS "-ffunction-sections -fdata-sections")
endif()

# -----------------------------------------

# Enable profiling (-pg) (This feature is not supported currently)
# set(USER_COMPILE_PROFILING_ENABLE )

# -----------------------------------------

# Verbose (-v)
set(USER_COMPILE_VERBOSE )

# Support ANSI_PROGRAM (-ansi)
set(USER_COMPILE_ANSI )

# Add any compiler options that are not covered by the above variables, they will be added as extra compiler options
# To enable profiling -pg [ for gprof ]  or -p [ for prof information ]
set(USER_COMPILE_OTHER_FLAGS "-mcpu=cortex-r52 -DARMR52 -mfloat-abi=hard -mfpu=vfpv3-d16")

# -----------------------------------------

# Linker options
# Do not use the standard system startup files when linking.
# The standard system libraries are used normally, unless -nostdlib or -nodefaultlibs is used. (-nostartfiles)
set(USER_LINK_NO_START_FILES )

# Do not use the standard system libraries when linking. (-nodefaultlibs)
set(USER_LINK_NO_DEFAULT_LIBS )

# Do not use the standard system startup files or libraries when linking. (-nostdlib)
set(USER_LINK_NO_STDLIB )

# Omit all symbol information. (-s)
set(USER_LINK_OMIT_ALL_SYMBOL_INFO )


# -----------------------------------------

# Add any libraries to be linked below, they will be added as extra libraries.
# User needs to update USER_LINK_DIRECTORIES below with these library search paths.
set(USER_LINK_LIBRARIES
)

# Add any directories to look for the libraries to be linked.
# Example 1: Adding /proj/compression/lib will pass -L/proj/compression/lib to the linker.
# Example 2: Adding ../../common/lib will consider the path as relative to this directory and will pass the path to -L option.
set(USER_LINK_DIRECTORIES
"../../sensor_lib/build"
)

# -----------------------------------------

set(USER_LINKER_SCRIPT "${CMAKE_SOURCE_DIR}/lscript.ld")

# Add linker options to be passed, they will be added as extra linker options
# Example : Adding -s will pass -s to the linker.
set(USER_LINK_OTHER_FLAGS )

# -----------------------------------------

###   END OF USER SETTINGS SECTION ###
###   DO NOT EDIT BEYOND THIS LINE ###

set(USER_COMPILE_OPTIONS
    " ${USER_COMPILE_WARNINGS_ALL}"
    " ${USER_COMPILE_WARNINGS_EXTRA}"
    " ${USER_COMPILE_WARNINGS_AS_ERRORS}"
    " ${USER_COMPILE_WARNINGS_CHECK_SYNTAX_ONLY}"
    " ${USER_COMPILE_WARNINGS_PEDANTIC}"
    " ${USER_COMPILE_WARNINGS_PEDANTIC_AS_ERRORS}"
    " ${USER_COMPILE_WARNINGS_INHIBIT_ALL}"
    " ${USER_COMPILE_OPTIMIZATION_LEVEL}"
    " ${USER_COMPILE_OPTIMIZATION_OTHER_FLAGS}"
    " ${USER_COMPILE_DEBUG_LEVEL}"
    " ${USER_COMPILE_DEBUG_OTHER_FLAGS}"
    " ${USER_COMPILE_VERBOSE}"
    " ${USER_COMPILE_ANSI}"
    " ${USER_COMPILE_OTHER_FLAGS}"
)
foreach(entry ${USER_UNDEFINED_SYMBOLS})
    list(APPEND USER_COMPILE_OPTIONS " -U${entry}")
endforeach()

set(USER_LINK_OPTIONS
    " ${USER_LINKER_NO_START_FILES}"
    " ${USER_LINKER_NO_DEFAULT_LIBS}"
    " ${USER_LINKER_NO_STDLIB}"
    " ${USER_LINKER_OMIT_ALL_SYMBOL_INFO}"
    " ${USER_LINK_OTHER_FLAGS}"
)
